### ISSUE TITLE
Large file (eg: 2.04 GB) upload fails

### ISSUE THREAD

**Issue by kzshantonu** [benbusby/yeetfile#14]
Caddyfile:

```
yeet.doma.in {
    encode zstd gzip
    reverse_proxy localhost:15379 {
        header_up Host {upstream_hostport}
    }
}
```

Envs:

```
POSTGRES_HOST_AUTH_METHOD=md5
POSTGRES_USER=yeetfile
POSTGRES_PASSWORD=oFCArobgmhpGyffxivkLxNd4GOGD4cSM
POSTGRES_DB=yeetfile
YEETFILE_STORAGE=local
YEETFILE_DB_HOST=db
YEETFILE_DB_PORT=5432
YEETFILE_DB_USER=yeetfile
YEETFILE_DB_PASS=oFCArobgmhpGyffxivkLxNd4GOGD4cSM
YEETFILE_DB_NAME=yeetfile
YEETFILE_SERVER_SECRET='ISqG8zSnROS8pTT9JCR/mTV83xqpfFN2P9mvOCEZTZI='
YEETFILE_SESSION_AUTH_KEY='7evr7bFiHJ+iKj9UfvKpSXgC0RKvCLZjpVN2UoY+GHk='
YEETFILE_SESSION_ENC_KEY='BxoDVwYJfMp+nXCmIk6U6+JG+4iYrTe3PvLoHBxDjFM='
YEETFILE_SERVER_PASSWORD='4rROBTFPlJZUZ0LA0Wq2lz0ohCpY8dCipBAl0b1MHV'
YEETFILE_CACHE_MAX_SIZE=1000000000
YEETFILE_CACHE_MAX_FILE_SIZE=100000000
YEETFILE_DOMAIN='https://yeet.doma.in'
YEETFILE_DEBUG=1
```

Log:

```
yeetfile  | 2025/02/01 22:20:59 POST /api/send/u
yeetfile  | 2025/02/01 22:21:00 POST /api/send/u/file_ebko7mh6w0vg/3
yeetfile  | 2025/02/01 22:21:00 POST /api/send/u/file_ebko7mh6w0vg/1
yeetfile  | 2025/02/01 22:21:00 POST /api/send/u/file_ebko7mh6w0vg/2
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 Retrying (attempt 2)
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 Retrying (attempt 3)
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 Retrying (attempt 4)
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 Retrying (attempt 5)
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 Retrying (attempt 6)
yeetfile  | 2025/02/01 22:21:00 Error: Post "uploads": unsupported protocol scheme ""
yeetfile  | 2025/02/01 22:21:00 [YF Send] Chunk upload err: exceeded maximum attempts
yeetfile  | 2025/02/01 22:21:00 Deleting file by metadata (B2 errors are OK)
yeetfile  | 2025/02/01 22:21:00 file_ebko7mh6w0vg deleted from cache
yeetfile  | 2025/02/01 22:21:00 Failed to delete B2 file (id: 8f43944e330c584f1df8bfc0017f3bfdd4c33580167ac0fbe0d92fb221f98c703f1b96154974de358701cd96d452e21de46cd80c46b12faf5f9ab8e61c096306294353f809c4360efcd14ec489b7b8ab612ae96a, metadata id: file_ebko7mh6w0vg)
yeetfile  | 2025/02/01 22:21:00 file_ebko7mh6w0vg metadata deleted
yeetfile  | 2025/02/01 22:21:00 file_ebko7mh6w0vg B2 info deleted
yeetfile  | 2025/02/01 22:21:00 file_ebko7mh6w0vg expiry fields deleted
yeetfile  | 2025/02/01 22:21:00 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:00 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:00 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:00 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:01 POST /api/send/u/file_ebko7mh6w0vg/4
yeetfile  | 2025/02/01 22:21:01 POST /api/send/u/file_ebko7mh6w0vg/5
yeetfile  | 2025/02/01 22:21:01 POST /api/send/u/file_ebko7mh6w0vg/6
yeetfile  | 2025/02/01 22:21:01 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:01 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:01 POST /api/send/u/file_ebko7mh6w0vg/7
yeetfile  | 2025/02/01 22:21:01 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:01 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:01 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:01 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:02 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:02 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:02 POST /api/send/u/file_ebko7mh6w0vg/8
yeetfile  | 2025/02/01 22:21:02 POST /api/send/u/file_ebko7mh6w0vg/9
yeetfile  | 2025/02/01 22:21:02 POST /api/send/u/file_ebko7mh6w0vg/10
yeetfile  | 2025/02/01 22:21:02 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:02 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:02 No metadata found for id: file_ebko7mh6w0vg
yeetfile  | 2025/02/01 22:21:02 [YF Send] Metadata err: no metadata found
yeetfile  | 2025/02/01 22:21:02 [YF Send] Chunk reader err: unexpected EOF
yeetfile  | 2025/02/01 22:21:04 CRON: Running 'limiter' task...
yeetfile  | 2025/02/01 22:21:04 'limiter' task completed at Sat, 01 Feb 2025 22:21:04 UTC
yeetfile  | 2025/02/01 22:21:04 CRON: Running 'expiry' task...
yeetfile  | 2025/02/01 22:21:04 'expiry' task completed at Sat, 01 Feb 2025 22:21:04 UTC
```

**Comment by kzshantonu** [comment]
Compose:

```
services:

  api:
    image: ghcr.io/benbusby/yeetfile:latest
    container_name: yeetfile
    restart: unless-stopped
    ports:
      - 127.0.0.1:15379:8090
    depends_on:
      db:
        condition: service_healthy
    env_file: ./yeetfile.env
    volumes:
      - ./volumes/yeetfile/uploads:/app/uploads

  db:
    image: postgres:16-alpine
    container_name: yeetfile-db
    restart: unless-stopped
    env_file: ./db.env
    volumes:
      - ./volumes/yeetfile/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
```

**Comment by zarevskaya** [comment]
Add these lines in envs.

YEETFILE_DEFAULT_USER_SEND=-1 
-1 => unlimited 
or set it like that, for 15MB : 
YEETFILE_DEFAULT_USER_SEND=15000000

YEETFILE_DEFAULT_USER_STORAGE=-1 
-1 => unlimited 
or set it like that, for 5MB : 
YEETFILE_DEFAULT_USER_STORAGE=5000000

https://github.com/benbusby/yeetfile#general-environment-variables

**Comment by kzshantonu** [comment]
Nope. Same.

```
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
yeetfile     | 2025/02/03 15:32:42 Retrying (attempt 2)
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
yeetfile     | 2025/02/03 15:32:42 Retrying (attempt 3)
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
yeetfile     | 2025/02/03 15:32:42 Retrying (attempt 4)
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
yeetfile     | 2025/02/03 15:32:42 Retrying (attempt 5)
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
yeetfile     | 2025/02/03 15:32:42 Retrying (attempt 6)
yeetfile     | 2025/02/03 15:32:42 Error: Post "uploads": unsupported protocol scheme ""
```

**Comment by zarevskaya** [comment]
This compose work like a charm : 

```
services:

  api:
    image: ghcr.io/benbusby/yeetfile:latest
    container_name: yeetfile
    restart: unless-stopped
    ports:
      - 8090:8090
    expose:
      - 8090
    depends_on:
      db:
        condition: service_healthy
    environment:
      - YEETFILE_DEBUG=0
      - YEETFILE_STORAGE=local
      - YEETFILE_DEFAULT_USER_STORAGE=-1
      - YEETFILE_DEFAULT_USER_SEND=-1
      #- YEETFILE_SERVER_PASSWORD=MonMotDePasse
      - YEETFILE_MAX_NUM_USERS=-1
      - YEETFILE_DOMAIN=https://yeetfile.mondomaine.com
      - YEETFILE_HOST=0.0.0.0
      - YEETFILE_PORT=8090
      - YEETFILE_DB_USER=postgres
      - YEETFILE_DB_PASS=postgres
      - YEETFILE_DB_NAME=yeetfile
      - YEETFILE_DB_HOST=db
      - YEETFILE_DB_PORT=5432
      - YEETFILE_SERVER_SECRET=xxxxx  
      - YEETFILE_SESSION_AUTH_KEY=xxxx
      - YEETFILE_SESSION_ENC_KEY=xxxxx
      #- YEETFILE_EMAIL_ADDR=zarev@xxx.com
      #- YEETFILE_EMAIL_HOST=smtp.xxx.xxx
      #- YEETFILE_EMAIL_PORT=587
      #- YEETFILE_EMAIL_USER=zarev@xxx.com
      #- YEETFILE_EMAIL_PASSWORD=MonMotDePasse
      #- YEETFILE_EMAIL_NO_REPLY=zarev@xxx.com
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:16-alpine
    container_name: yeetfile-db
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yeetfile
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
```

Use this form in the compose for the key and server secret: 

    YEETFILE_SERVER_SECRET=igEXJoIU8PovjLuUYU4L3G9w7G0R4IkzlIHGiFsu61Q=
    YEETFILE_SESSION_AUTH_KEY=Lwm7P92zTXf+Q0dEfFZnUPn+8X8Hlu2MrrWHl/egi74=
    YEETFILE_SESSION_ENC_KEY=lGeQg6aoD9Or1NBsO17s10GKeD/RyS8QUZjyh1CkbX8=
